### ISSUE TITLE
Idle time is not correct

### ISSUE THREAD

**Issue by TheButlah** [vyfor/cord.nvim#119] opened 2024-11-15 00:48 UTC
### Description

I am using cord for the first time. The idle timeout doesn't seem correct. When set to 100, it takes 20 seconds. When set to 200, it takes ~45 seconds. The idle timeout is supposed to be in milliseconds, so something must be up.

### Operating system

MacOS Sonoma 14.6.1 (23G93)

### Neovim version

```markdown
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

### Steps to reproduce

My config is at https://github.com/TheButlah/init.lua/blob/95dcc3873f7d6a48065614e333f2ab7e65024898/lua/thebutlah/plugins/cord.lua

### Expected behavior

I expected the timeout to represent milliseconds.

### Actual behavior

The timeout appears to represent 200 milliseconds (or something)

### Minimal configuration

```Lua
return {
	"vyfor/cord.nvim",
	build = "./build || .\\build",
	event = "VeryLazy",
	opts = {
		timer = {
			reset_on_idle = true, -- Reset start timestamp on idle
			reset_on_change = false, -- Reset start timestamp on presence change
		},
		idle = {
			enable = true, -- Enable idle status
			show_status = true, -- Display idle status, disable to hide the rich presence on idle
			timeout = 100, -- Timeout in milliseconds after which the idle status is set, 0 to display immediately
			disable_on_focus = false, -- Do not display idle status when neovim is focused
			text = "Idle", -- Text to display when idle
			tooltip = "💤", -- Text to display when hovering over the idle image
		},
	},
}
```

**Comment by vyfor** [comment] 2024-11-15 08:28
Hi there,  

I couldn’t reproduce this bug on my end. The timeout is indeed in milliseconds, so with such a low value, the idle status should appear almost immediately. 

That said, I noticed that in your config you’ve set `show_status` to [`false`](https://github.com/TheButlah/init.lua/blob/95dcc3873f7d6a48065614e333f2ab7e65024898/lua/thebutlah/plugins/cord.lua#L12C18-L12C23), which hides the presence when the idle status kicks in. AFAIK, Discord RPC enforces some rate limits (poorly documented), particularly for reconnections and clearing the presence. So it can take a while for the status to fully clear, and the more often you try to clear or reconnect, the longer the cooldown period becomes.

To verify this, you can set the said field to `true` and check the idle status directly without clearing it. Let me know how it goes!

**Comment by TheButlah** [comment] 2024-11-15 09:05
The same things happens when the field is true.

Are you on macos or linux?

**Comment by vyfor** [comment] 2024-11-15 09:10
No, I'm on Windows. I'll boot up a Linux VM and see how it behaves there.

**Comment by vyfor** [comment] 2024-11-15 09:24
Strangely, the idle status does not appear at all on Fedora.

**Comment by vyfor** [comment] 2024-11-15 09:41
I’ve found the root of the problem. The Lua function I’m using to get the elapsed time seems to behave differently on Unix systems compared to Windows, and goes back in 2018: https://github.com/LuaJIT/LuaJIT/issues/442
![image](https://github.com/user-attachments/assets/3227d629-f87a-49c4-abd6-ec6d9122cc2f)

**Comment by vyfor** [comment] 2024-11-15 10:12
@TheButlah, pushed a fix to master. Could you please verify that it works as expected?

**Comment by TheButlah** [comment] 2024-11-17 18:28
Just tested commit `c0d1dd1`. It works now! Thanks!

**Closed** 2024-11-17 18:28 UTC
Labels: bug
